#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2022-06-04 18:39:20.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("is.unnamed() works", {

  f <- kwb.utils:::is.unnamed

  expect_error(
    kwb.utils:::is.unnamed()
    # argument "x" is missing, with no default
  )

})
