#
# This file was generated by kwb.test::create_test_files(),
# launched by hsonne on 2024-02-16 08:26:32.982136.
# Please modify the dummy functions so that real cases are
# tested. Then, delete this comment.
#

test_that("nDims() works", {

  f <- kwb.utils:::nDims

  expect_error(
    f()
    # Argument "x" fehlt (ohne Standardwert)
  )

})
