#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2022-06-04 18:39:06.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("set_cache_dir() works", {

  f <- kwb.utils:::set_cache_dir

  expect_error(
    f()
    # argument "path" is missing, with no default
  )

})
