#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2022-06-04 18:39:18.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("getNamesOfObjectsInRDataFiles() works", {

  f <- kwb.utils:::getNamesOfObjectsInRDataFiles

  expect_error(
    kwb.utils:::getNamesOfObjectsInRDataFiles()
    # argument "files.rdata" is missing, with no default
  )

})
