#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2022-06-04 18:39:06.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("assignArgumentDefaults() works", {

  f <- kwb.utils:::assignArgumentDefaults

  expect_error(
    kwb.utils:::assignArgumentDefaults()
    # argument "FUN" is missing, with no default
  )

})
