#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hauke on 2019-08-07 07:51:56.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("clear_cache() works", {

  kwb.utils:::clear_cache()

})
