#
# This file was generated by kwb.test::create_test_files(), 
# launched by hsonne on 2024-02-16 08:26:26.874512.
# Please modify the dummy functions so that real cases are
# tested. Then, delete this comment.
#

test_that("callWithData() works", {

  f <- kwb.utils::callWithData

  expect_error(
    f()
    # Argument "FUN" fehlt (ohne Standardwert)
  )

})
