#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2022-06-04 18:39:21.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that(".guessSeparator.2() works", {

  f <- kwb.utils:::.guessSeparator.2

  expect_error(
    f()
    # argument "textlines" is missing, with no default
  )

})
